/* ===========================================================================

    Copyright (c) The ART Development Team
    --------------------------------------

    For a comprehensive list of the members of the development team, and a
    description of their respective contributions, see the file
    "ART_DeveloperList.txt" that is distributed with the libraries.

    This file is part of the Advanced Rendering Toolkit (ART) libraries.

    ART is free software: you can redistribute it and/or modify it under the
    terms of the GNU General Public License as published by the Free Software
    Foundation, either version 3 of the License, or (at your option) any
    later version.

    ART is distributed in the hope that it will be useful, but WITHOUT ANY
    WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with ART.  If not, see <http://www.gnu.org/licenses/>.

=========================================================================== */

#ifndef _ARCINTERESECTION_H_
#define _ARCINTERESECTION_H_

#include "ART_Foundation.h"

ART_MODULE_INTERFACE(ArcIntersection)

#include "ArcSurfacePoint.h"

@interface ArcIntersection
        : ArcSurfacePoint <ArpRayEndpoint, ArpIntersectionEvalEnv>
{
@public
    double  t;
    double  worldspace_cosine;
    Ray3D   worldspace_incoming_ray;
    Ray3D   objectspace_incoming_ray;
#ifdef WITH_RSA_STATISTICS
    unsigned int  intersectionTests;
    unsigned int  traversalSteps;
#endif
}

- (BOOL) evaluateEmission
        : (      ArcPointContext *) illuminatedPoint
        // path direction assumed to be arpathdirection_from_eye
        : (const ArWavelength *) wavelength
        : (      ArSamplingRegion *) samplingRegion
        : (      ArLightSample *) lightSample
        ;

@end

#define ARCINTERSECTION_TRAVERSALSTATE \
    ARCSURFACEPOINT_TRAVERSALSTATE
#define ARCINTERSECTION_NEXT(__intersection) \
    ((ArcIntersection *)(ARCSURFACEPOINT_NEXT(__intersection)))
#define ARCINTERSECTION_PREV(__intersection) \
    ((ArcIntersection *)(ARCSURFACEPOINT_PREV(__intersection)))
#define ARCINTERSECTION_TEXTURE_COORDS \
    ARCSURFACEPOINT_TEXTURE_COORDS
#define ARCINTERSECTION_OBJECTSPACE_POINT \
    ARCSURFACEPOINT_OBJECTSPACE_POINT
#define ARCINTERSECTION_SET_OBJECTSPACE_POINT \
    ARCSURFACEPOINT_SET_OBJECTSPACE_POINT
#define ARCINTERSECTION_OBJECTSPACE_NORMAL \
    ARCSURFACEPOINT_OBJECTSPACE_NORMAL
#define ARCINTERSECTION_SET_OBJECTSPACE_NORMAL \
    ARCSURFACEPOINT_SET_OBJECTSPACE_NORMAL
#define ARCINTERSECTION_WORLDSPACE_POINT \
    ARCSURFACEPOINT_WORLDSPACE_POINT
#define ARCINTERSECTION_SET_WORLD_POINT \
    ARCSURFACEPOINT_SET_WORLDSPACE_POINT
#define ARCINTERSECTION_WORLDSPACE_NORMAL \
    ARCSURFACEPOINT_WORLDSPACE_NORMAL
#define ARCINTERSECTION_SET_WORLDSPACE_NORMAL \
    ARCSURFACEPOINT_SET_WORLDSPACE_NORMAL

#define ARCINTERSECTION_ENVIRONMENT_MATERIAL \
    ARCSURFACEPOINT_ENVIRONMENT_MATERIAL

#define ARCINTERSECTION_SURFACE_MATERIAL \
    ARCSURFACEPOINT_SURFACE_MATERIAL
#define ARCINTERSECTION_SURFACETYPE \
    ARCSURFACEPOINT_SURFACETYPE

#define ARCINTERSECTION_VOLUME_MATERIAL_INTO_REF \
    ARCSURFACEPOINT_VOLUME_MATERIAL_INSIDE_REF
#define ARCINTERSECTION_VOLUME_MATERIAL_INTO \
    ARCSURFACEPOINT_VOLUME_MATERIAL_INSIDE

#define ARCINTERSECTION_VOLUME_MATERIAL_FROM_REF \
    ARCSURFACEPOINT_VOLUME_MATERIAL_OUTSIDE_REF
#define ARCINTERSECTION_VOLUME_MATERIAL_FROM \
    ARCSURFACEPOINT_VOLUME_MATERIAL_OUTSIDE

#define ARCINTERSECTION_VOLUME_MATERIAL_INTO_RETAIN_REF(__i,__r) \
    COPY_NODE_REF( \
        *(__r), \
        ARCINTERSECTION_VOLUME_MATERIAL_INTO_REF(__i) \
        );

#define ARCINTERSECTION_VOLUME_MATERIAL_FROM_RETAIN_REF(__i,__r) \
    COPY_NODE_REF( \
        *(__r), \
        ARCINTERSECTION_VOLUME_MATERIAL_FROM_REF(__i) \
        );

#define ARCINTERSECTION_PHASEINTERFACE\
    ARCSURFACEPOINT_PHASEINTERFACE

#define ARCINTERSECTION_PHASE_INTERFACE_HAS_REALVALUED_IOR(_i) \
    ARCPHASEINTERFACE_HAS_REALVALUED_IOR(*ARCINTERSECTION_PHASEINTERFACE(_i) )
#define ARCINTERSECTION_PHASE_INTERFACE_HAS_COMPLEX_IOR(_i) \
    ARCPHASEINTERFACE_HAS_COMPLEX_IOR(*ARCINTERSECTION_PHASEINTERFACE(_i) )

#define ARCINTERSECTION_SHAPE \
    ARCSURFACEPOINT_SHAPE
#define ARCINTERSECTION_TRAFO \
    ARCSURFACEPOINT_TRAFO
#define ARCINTERSECTION_FACE_TYPE \
    ARCSURFACEPOINT_FACE_TYPE
#define ARCINTERSECTION_FACE_ID \
    ARCSURFACEPOINT_FACE_ID

#define ARCINTERSECTION_T(__intersection) \
    (__intersection)->t

#define ARCINTERSECTION_OBJECTSPACE_INCOMING_RAY(__intersection) \
    (__intersection)->objectspace_incoming_ray
#define ARCINTERSECTION_OBJECTSPACE_INCOMING_RAY_VECTOR(__intersection) \
    RAY3D_VECTOR(ARCINTERSECTION_OBJECTSPACE_INCOMING_RAY(__intersection))
#define ARCINTERSECTION_OBJECTSPACE_INCOMING_VECTOR \
    ARCINTERSECTION_OBJECTSPACE_INCOMING_RAY_VECTOR

#define ARCINTERSECTION_WORLDSPACE_INCOMING_RAY(__intersection) \
    (__intersection)->worldspace_incoming_ray
#define ARCINTERSECTION_WORLDSPACE_INCOMING_RAY_VECTOR(__intersection) \
    RAY3D_VECTOR(ARCINTERSECTION_WORLDSPACE_INCOMING_RAY(__intersection))
#define ARCINTERSECTION_WORLDSPACE_INCOMING_VECTOR \
    ARCINTERSECTION_WORLDSPACE_INCOMING_RAY_VECTOR
#define ARCINTERSECTION_WORLDSPACE_VECTOR \
    ARCINTERSECTION_WORLDSPACE_INCOMING_RAY_VECTOR
#define ARCINTERSECTION_WORLDSPACE_INCOMING_COSINE(__intersection) \
    (__intersection)->worldspace_cosine
#define ARCINTERSECTION_WORLDSPACE_COSINE \
    ARCINTERSECTION_WORLDSPACE_INCOMING_COSINE

#define ARCINTERSECTION_SURFACE_IS_REFRACTIVE \
    ARCSURFACEPOINT_SURFACE_IS_REFRACTIVE
#define ARCINTERSECTION_SURFACE_IS_EMITTER \
    ARCSURFACEPOINT_SURFACE_IS_EMITTER
#define ARCINTERSECTION_SURFACE_IS_DIRECT_ILLUMINATION_MATTE \
    ARCSURFACEPOINT_SURFACE_IS_DIRECT_ILLUMINATION_MATTE
#define ARCINTERSECTION_SURFACE_IS_MATTE \
    ARCSURFACEPOINT_SURFACE_IS_MATTE

#define ARCINTERSECTION_TEXTURE_COORDS_ARE_VALID \
    ARCSURFACEPOINT_TEXTURE_COORDS_ARE_VALID
#define ARCINTERSECTION_OBJECTSPACE_POINT_IS_VALID \
    ARCSURFACEPOINT_OBJECTSPACE_POINT_IS_VALID
#define ARCINTERSECTION_OBJECTSPACE_NORMAL_IS_VALID \
    ARCSURFACEPOINT_OBJECTSPACE_NORMAL_IS_VALID
#define ARCINTERSECTION_WORLDSPACE_POINT_IS_VALID \
    ARCSURFACEPOINT_WORLDSPACE_POINT_IS_VALID
#define ARCINTERSECTION_WORLDSPACE_NORMAL_IS_VALID \
    ARCSURFACEPOINT_WORLDSPACE_NORMAL_IS_VALID

#define ARCINTERSECTION_FLAG_TEXTURE_COORDS_AS_VALID \
    ARCSURFACEPOINT_FLAG_TEXTURE_COORDS_AS_VALID
#define ARCINTERSECTION_FLAG_OBJECTSPACE_POINT_AS_VALID \
    ARCSURFACEPOINT_FLAG_OBJECTSPACE_POINT_AS_VALID
#define ARCINTERSECTION_FLAG_OBJECTSPACE_NORMAL_AS_VALID \
    ARCSURFACEPOINT_FLAG_OBJECTSPACE_NORMAL_AS_VALID
#define ARCINTERSECTION_FLAG_WORLD_POINT_AS_VALID \
    ARCSURFACEPOINT_FLAG_WORLDSPACE_POINT_AS_VALID
#define ARCINTERSECTION_FLAG_WORLD_NORMAL_AS_VALID \
    ARCSURFACEPOINT_FLAG_WORLDSPACE_NORMAL_AS_VALID

#define ARCINTERSECTION_NEXT_PTR(__intersection)   ARCSURFACEPOINT_NEXT(__intersection)
#define ARCINTERSECTION_PREV_PTR(__intersection)   ARCSURFACEPOINT_PREV(__intersection)

#define ARCINTERSECTION_OBJECTSPACE_PX(__i)  XC(ARCINTERSECTION_OBJECTSPACE_POINT(__i))
#define ARCINTERSECTION_OBJECTSPACE_PY(__i)  YC(ARCINTERSECTION_OBJECTSPACE_POINT(__i))
#define ARCINTERSECTION_OBJECTSPACE_PZ(__i)  ZC(ARCINTERSECTION_OBJECTSPACE_POINT(__i))
#define ARCINTERSECTION_OBJECTSPACE_NX(__i)  XC(ARCINTERSECTION_OBJECTSPACE_NORMAL(__i))
#define ARCINTERSECTION_OBJECTSPACE_NY(__i)  YC(ARCINTERSECTION_OBJECTSPACE_NORMAL(__i))
#define ARCINTERSECTION_OBJECTSPACE_NZ(__i)  ZC(ARCINTERSECTION_OBJECTSPACE_NORMAL(__i))
#define ARCINTERSECTION_WORLDSPACE_PX(__i)   XC(ARCINTERSECTION_WORLDSPACE_POINT(__i))
#define ARCINTERSECTION_WORLDSPACE_PY(__i)   YC(ARCINTERSECTION_WORLDSPACE_POINT(__i))
#define ARCINTERSECTION_WORLDSPACE_PZ(__i)   ZC(ARCINTERSECTION_WORLDSPACE_POINT(__i))
#define ARCINTERSECTION_WORLDSPACE_NX(__i)   XC(ARCINTERSECTION_WORLDSPACE_NORMAL(__i))
#define ARCINTERSECTION_WORLDSPACE_NY(__i)   YC(ARCINTERSECTION_WORLDSPACE_NORMAL(__i))
#define ARCINTERSECTION_WORLDSPACE_NZ(__i)   ZC(ARCINTERSECTION_WORLDSPACE_NORMAL(__i))

#endif // _ARCINTERESECTION_H_

// ===========================================================================
